#namespace
apiVersion: v1
kind: Namespace
metadata: 
  name: dev
  labels:
    ns: dev
---
apiVersion: v1
kind: Pod
metadata: 
  name: testpod
  namespace: dev
  labels:
    app: testpod
spec:
  containers:
  - name: nginx-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: nodeapp-ctr
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: dev-svc
  namespace: dev
spec: 
  type: NodePort
  selector: 
    app: testpod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: nginx
  - port: 8080
    targetPort: 8080
    nodePort: 30081
    name: java



