apiVersion: apps/v1
kind: Deployment  
metadata:
  name: rh-fe
  namespace: dev
  labels: 
    app: rh-fe-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector: 
    matchLabels:
      app: rh-fe-app
  template:
    metadata:
      name: rh-fe-app-pod
      labels:
        app: rh-fe-app
    spec:
      nodeSelector:
        node: worker1
       # name: webhost
      containers:
      - name: rh-fe-app-ctr
        # image: shubham808/retailhub-frontend:0.0.1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: rh-fe-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: rh-fe-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
