apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpaapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  hpapod
  template:
    metadata:
      labels:
        app:  hpapod
    spec:
      containers:
      - name: hpa-ctr
        image: k8s.gcr.io/hpa-example
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: hpa-svc
  namespace: dev
spec: 
  selector:
    app: hpapod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31006

