apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapp
  labels: 
    app: mavenwebapp
  namespace: test-ns

spec:
  containers:
  - name: mavenwebapp-ctr
    image: nginx
    ports:
    - containerPort: 80
