apiVersion: v1
kind: Service
metadata:
  name: fe-app-svc
  labels:
    app: fe-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: fe-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  labels:
    app: fe-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-app
        image: shubham808/chap-test-live
        ports:
        - containerPort: 4000