apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  labels:
    team: test-team
---
apiVersion: v1
kind: Pod
metadata: 
  name: mavenapp
  namespace: test-ns
  labels:
    app: mavenapp
spec:
  container:
  - name: mavenapp-ctr
    image: dockerhandson/maven-webapplication:1
    ports:
    - containerport: 8080


---
apiVersion: v1
kind: Service
metadata: 
  name: maven-svc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mavenapp
  ports:
  - port: 80 # Clusterip
    targetport: 8080  #containerip

  














