apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-mongo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-ctr
        image: shubham808/spring-boot-mongo:tagname
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            memory: "300Mi"
            cpu: "500m"
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb123
        - name: MONGO_DB_HOSTNAME
          value: mongo-state-svc
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: dev
spec:
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30011    
  type: NodePort

