apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
  namespace: nginx
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure

          containers:
          - name: demo-cronjob-ctr
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              echo "Background Job Started at $(date)"
              mkdir -p /backups
              mkdir -p /demo-data
              cp -r /demo-data/* /backups/ || true
              echo "Background Job Completed at $(date)"

            volumeMounts:
            - name: data-volume
              mountPath: /demo-data
            - name: backup-volume
              mountPath: /backups

          volumes:
          - name: data-volume
            hostPath:
              path: /demo-data
              type: DirectoryOrCreate
          - name: backup-volume
            hostPath:
              path: /backups
              type: DirectoryOrCreate