apiVersion: v1
kind: Pod
metadata:
  name: mavenapp
  namespace: test
  labels:
    app: mavenapp
spec:
  containers:
  - name: mavenapp-ctr
    image: shubham808/jenkins:champ
    ports:
    - containerPort: 8080  # Correct indentation
---
apiVersion: v1
kind: Service
metadata:
  name: maven-nodport-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80  # clusterport
    targetPort: 8080  # container port
    nodePort: 30033  # range of port 30000 to 32767
