apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-ctr
        image: shubham808/jenkins:champ
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1056Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     server: 3.6.95.39
#     path: /mnt/nfs_share/jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 80 #assign 8080 first but not work later work with 80
    targetPort: 8080
    nodePort: 30012
