apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
  namespace: dev 
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadwriteMany
  nfs:
    server: 3.6.95.39
    path: /mnt/nfs_share








