apiVersion: v1
kind: ReplicationController 
metadata: 
  name: demorc
  namespace: test-ns
spec:
  replicas: 3
  selector: 
    app: demorc
  template: 
    metadata:
      name: demorcpod
      labels:
        app: demorc
      spec:
        containers:
        - name: mavenapp-ctr
          image: shubham808/corporateraasta-live
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demorc-svc
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: demorc
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 31000