apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-ds
  namespace: test
  labels:
    app: logging
spec: 
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging-agent
        image: fluentd
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 24224
---
apiVersion: v1
kind: Service
metadata:
  name: logging-ds-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: logging
  ports:
  - port: 80
    targetPort: 24224
    nodePort: 31004
