apiVersion: apps/v1
kind: Deployment  
metadata:
  name: rh-fe
  namespace: dev
  labels: 
    app: rh-fe-app
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector: 
    matchLabels:
      app: rh-fe-app
  template:
    metadata:
      name: rh-fe-app-pod
      labels:
        app: rh-fe-app
    spec: 
      containers:
      - name: rh-fe-app-ctr
        # image: shubham808/retailhub-frontend:0.0.1
        image: dockerhandson/java-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata: 
  name: rh-fe-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: rh-fe-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
