apiVersion: apps/v1
kind: Deployment  
metadata:
  name: rh-fe
  namespace: dev
  labels: 
    app: rh-fe-app
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: rh-fe-app
  template:
    metadata:
      name: rh-fe-app-pod
      labels:
        app: rh-fe-app
    spec: 
      containers:
      - name: rh-fe-app-ctr
        image: shubham808/chaperone-admin-live
        ports:
        - containerPort: 5000
---
apiVersion: v1 
kind: Service 
metadata: 
  name: rh-fe-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: rh-fe-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
