apiVersion: apps/v1
kind: Deployment 
metadata:
  name: rh-deployment-ru
  namespace: test
spec:
  replicas: 2
  revisionHistoryLimit: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: rh-app-ru
  template:
    metadata:
      name: rh-ru-pod
      labels:
        app: rh-app-ru
    spec:
      containers:
      - name: rh-app-ru-ctr
        image: dockerhandson/java-web-app:1
        #image: shubham808/retailhub-frontend:0.0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 20Mi
---
apiVersion: v1
kind: Service 
metadata:
  name: rh-ru-svc
  namespace: test
spec: 
  selector:
    app: rh-app-ru
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31002










