apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: mongodb
  namespace: test
spec:
  replicas: 
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-ctr
          image: mongo
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDBMONGO_INITDB_ROOT_USERNAME
            value: devdb
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: shubham94
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

