apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deplyment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-ctr
        image: dockerhandson/spring-boot-app:1
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo-svc.test.svc.cluster.local
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: shubham94
        
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: spring-boot-mongo:1
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31017

