apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: dev
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012
    protocol: TCP
  selector:
    app: jenkins
