apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapplication
  namespace: dev
  labels:
    app: mavenapp
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate  # "Recreate" will ensure that the old pod is deleted before creating a new one.
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:  # Removed unused `name: mavenapp-pod`, as `metadata.labels` is sufficient for matching the pod.
        app: mavenapp
    spec:
      imagePullSecrets:
      - name: mydockerhub
      containers:
      - name: mavenapp-ctr
        image: shubham808/java-web-app:react
        #image: shubham808/java-web-app:nexus  # private repo | port: 8081 | not working
        #image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5  
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service 
metadata:
  name: mavenapp-svc-np
  namespace: dev
spec:
  selector:
    app: mavenapp
  type: NodePort
  ports:
  - name: mavenapp-port
    port: 80
    targetPort: 80
    nodePort: 30001


