apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapplication
  namespace: dev
  labels:
    app: mavenapp
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      name: mavenapp-pod
      #namespace: dev
      labels: 
        app: mavenapp
    spec:
      containers:
      - name: mavenapp-ctr
        image: shubham808/java-web-app:nexus
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: mydockerhub
---
apiVersion: v1
kind: Service 
metadata:
  name: mavenapp-svc-np
  namespace: dev
spec:
  selector:
    app: mavenapp
  type: NodePort
  ports:
  - name: mavenapp-port
    port: 80
    targetPort: 8081
    nodePort: 30001


