apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  ClusterIP: None # headless service
  selector:
    app: mysql  
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    