apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql # Port name is required for StatefulSets to work properly
  clusterIP: None # Defines this as a Headless Service
  selector:
    app: mysql
    