apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  namespace: test-ns
  labels: 
    app: nodeapp
spec:
  containers:
  - name: nodeapp-ctr
    image:
    port:
    - containerPort: 9000