apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  namespace: test-ns
  labels: 
    app: nodeapp
spec:
  containers:
  - name: nodeapp-ctr
    image: dockerhandson/node-app-mss:1
    ports:
    - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-nodeport-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 30077