apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  namespace: test-ns
  labels: 
    app: nodeapp
spec:
  containers:
  - name: nodeapp-ctr
    image: dockerhandson/node-app-mss:1
    ports:
    - containerPort: 9981