apiVersion: v1 
kind: ConfigMap 
metadata:
  name: mongodb-configmap
  namespace: dev
data:
  mongodbuser: devdb
  mongodbpasswd: shubham94
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-ctr
        image: mongo
        ports:
        - containerPort: 27017
        env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: devdb
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: mongodbuser
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: shubham94
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: mongodbpasswd 
      #   resources:
      #     requests:
      #       cpu: "200m"
      #       memory: "100Mi"
      #     limits:
      #       cpu: "400m"
      #       memory: "200Mi"
      #   volumeMounts:
      #   - name: mongodb-pvc-vol
      #     mountPath: /data/db
      # volumes:
      # - name: mongodb-pvc-vol
      #   persistentVolumeClaim:
      #     claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
#   namespace: dev
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   accessModes:
#   - ReadWriteMany
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv-dev
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteMany
#   nfs:
#     server: 3.6.95.39
#     path: /mnt/nfs_share



