apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javaapp
  namespace: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      name: javaapp-pod
      labels:
        app: javaapp
    spec:
      containers:
      - name: java-ctr
        image: dockerhandson/java-web-app:1
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            cpu: "300m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: javapp-svc
  namespace: dev 
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30013
   


