apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: java-configmap-vol
  namespace: dev 
data:
  tomcat-users.xml: |  # Multiline string not key-value
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                version="1.0">
    <user username="shubham" password="changeinpodv.1" roles="admin-gui,manager-gui"/>
    </tomcat-users>
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javaapp
  namespace: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      name: javaapp-pod
      labels:
        app: javaapp
    spec:
      containers:
      - name: java-ctr
        image: dockerhandson/java-web-app:1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: configmap-vol 
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"      
      volumes:
      - name: configmap-vol 
        configMap:
          name: java-configmap-vol
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata: 
  name: javapp-svc
  namespace: dev 
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30013
   


