apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-configmap
  namespace: dev
data:
  MONGO_INITDB_ROOT_USERNAME: devdb
  MONGO_INITDB_ROOT_PASSWORD: shubham94
---
apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: mongodb
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-ctr
          image: mongo
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            # value: devdb
            valueFrom:
              configMapKeyRef:
                name: spring-configmap
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            # value: shubham94
            valueFrom:
              configMapKeyRef:
                name: spring-configmap
                key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
          - name: mongodb-nfs-vol
            mountPath: /data/db
      volumes:
      - name: mongodb-nfs-vol
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dev
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteMany
#   nfs:
#     server: 3.6.95.39
#     path: /mnt/nfs_share/mongodb
