apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-rs
  namespace: test
  labels:
  app: nodejs-rs
  env: test
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nodejsapp
      env: test
  template: #pod
    metadata:
      name: nodeapppod
      labels: 
        app: nodejsapp
        env: test

    spec:
      containers:
      - name: nodejsapp-ctr
        image: shubham808/rh-fe-k8:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-rs-svc
  namespace: test
  labels:
  app: nodejs-rs-svc
  env: test
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31002
  